[package]
name = "fwht"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"

[dev-dependencies]
rand = "0.8.5"
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false
